version: "3.4"

services:
  db:
    container_name: database
    image: postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - web
      - migration
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: web
    ports:
      - "5432:5432"

  migrate:
    container_name: migrate
    env_file:
      - .env
    depends_on:
      - db
    image: server
    build: .
    networks:
      - migration
    volumes:
      - migrationdata:/app/sampleapp/migrations
    command: python3 /app/manage.py migrate
    ports:
      - "8001:8000"

  server:
    container_name: server
    env_file:
      - .env
    depends_on:
      - db
    image: server
    build: .
    networks:
      - web
    volumes:
      - sqlitedata:/app/sqlite
    ports:
      - "8000:8000"

volumes:
  pgdata:
  sqlitedata:
  migrationdata:


networks:
  migration:
  web:
