version: '3'

env:
  TAG:
    sh: date "+%y-%m-%d-%H.%M"

tasks:
  build:
    cmds:
      - docker build -t devops-final-task:{{.TAG}} --target builder .
      - echo Success build. name=devops-final-task:{{.TAG}}

  build-tests:
    cmds:
      - docker build -t devops-final-task:{{.TAG}} --target tests .
      - echo Success tests build. name=devops-final-task:{{.TAG}}

  build-prod:
    cmds:
      - docker build -t devops-final-task:{{.TAG}} --target prod .
      - echo Success prod build. name=devops-final-task:{{.TAG}}

  run-builder:
    cmds:
      - docker run -it devops-final-task:{{.TAG}} --target builder 

  run-test:
    cmds:
      - docker run -it devops-final-task:{{.TAG}} --target tests

  run-server:
    cmds:
      - docker run -it devops-final-task:{{.TAG}} --target prod

  run-compose-prod:
    cmds:
      - docker compose up prod

  run-compose-migrate:
    cmds:
      - docker compose up migrate 

  down:
    cmds:
      - docker compose down

