apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: denisov-certificate
spec:
  dnsNames:
  - 'denisov.dacdevops.ru'
  issuerRef:
    kind: ClusterIssuer
    name: yc-clusterissuer
  secretName: denisov-cert