apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mulenokv-certificate
spec:
  dnsNames:
  - 'mulenokv.dacdevops.ru'
  issuerRef:
    kind: ClusterIssuer
    name: yc-clusterissuer
  secretName: mulenokv-cert