apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mulenokv-namespace
images:
- name: nginx
  newName: nginx
  newTag: 1.23.2-alpine
- name: sample-app
  newName: mulenokv/sample-app
  newTag: 6203ca1147c69bac0031a31f657ea4107155fa48
- name: sampleapp
  newTag: main

resources:
- ../../base
- namespace.yml
- ingress.yml
- certificate.yml
